#!/bin/bash

if [[ $1 ]]; then
curl -s "https://api.certspotter.com/v1/issuances?domain=$1&expand=dns_names" | jq '.[].dns_names[]' | sed 's/\"//g' | sed 's/\*\.//g' | sort -u | grep "$1"

else
    echo "specify arguments"
fi
